# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: new/lab_3_const.xdc

# Block Designs: bd/design_test/design_test.bd
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_test || ORIG_REF_NAME==design_test} -quiet] -quiet

# IP: bd/design_test/ip/design_test_processing_system7_0_0/design_test_processing_system7_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_test_processing_system7_0_0 || ORIG_REF_NAME==design_test_processing_system7_0_0} -quiet] -quiet

# IP: bd/design_test/ip/design_test_ps7_0_axi_periph_0/design_test_ps7_0_axi_periph_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_test_ps7_0_axi_periph_0 || ORIG_REF_NAME==design_test_ps7_0_axi_periph_0} -quiet] -quiet

# IP: bd/design_test/ip/design_test_rst_ps7_0_50M_0/design_test_rst_ps7_0_50M_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_test_rst_ps7_0_50M_0 || ORIG_REF_NAME==design_test_rst_ps7_0_50M_0} -quiet] -quiet

# IP: bd/design_test/ip/design_test_xbar_0/design_test_xbar_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_test_xbar_0 || ORIG_REF_NAME==design_test_xbar_0} -quiet] -quiet

# IP: bd/design_test/ip/design_test_PmodOLED_0_0/design_test_PmodOLED_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_test_PmodOLED_0_0 || ORIG_REF_NAME==design_test_PmodOLED_0_0} -quiet] -quiet

# IP: bd/design_test/ip/design_test_axi_gpio_0_1/design_test_axi_gpio_0_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_test_axi_gpio_0_1 || ORIG_REF_NAME==design_test_axi_gpio_0_1} -quiet] -quiet

# IP: bd/design_test/ip/design_test_axi_gpio_0_2/design_test_axi_gpio_0_2.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_test_axi_gpio_0_2 || ORIG_REF_NAME==design_test_axi_gpio_0_2} -quiet] -quiet

# IP: bd/design_test/ip/design_test_auto_pc_0/design_test_auto_pc_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_test_auto_pc_0 || ORIG_REF_NAME==design_test_auto_pc_0} -quiet] -quiet

# XDC: bd/design_test/design_test_ooc.xdc
